Erro = type:WebSocketBadStatusException | message: Handshake status 200 OK | trace: [{'filename': 'c:\\Users\\jhefe\\OneDrive\\Documentos\\GitHub\\SRBRONLINE\\RewardEvents\\obs_events.py', 'name': 'notification', 'lineno': 219}, {'filename': 'C:\\Users\\jhefe\\OneDrive\\Documentos\\GitHub\\SRBRONLINE\\RewardEvents\\.venv\\Lib\\site-packages\\obsws_python\\reqs.py', 'name': '__init__', 'lineno': 18}, {'filename': 'C:\\Users\\jhefe\\OneDrive\\Documentos\\GitHub\\SRBRONLINE\\RewardEvents\\.venv\\Lib\\site-packages\\obsws_python\\baseclient.py', 'name': '__init__', 'lineno': 36}, {'filename': 'C:\\Users\\jhefe\\OneDrive\\Documentos\\GitHub\\SRBRONLINE\\RewardEvents\\.venv\\Lib\\site-packages\\websocket\\_core.py', 'name': 'connect', 'lineno': 253}, {'filename': 'C:\\Users\\jhefe\\OneDrive\\Documentos\\GitHub\\SRBRONLINE\\RewardEvents\\.venv\\Lib\\site-packages\\websocket\\_handshake.py', 'name': 'handshake', 'lineno': 57}, {'filename': 'C:\\Users\\jhefe\\OneDrive\\Documentos\\GitHub\\SRBRONLINE\\RewardEvents\\.venv\\Lib\\site-packages\\websocket\\_handshake.py', 'name': '_get_resp_headers', 'lineno': 147}] | time: 04/12/2022 11:36:13 
Erro = type: DownloadError | message: ERROR: Postprocessing: ffprobe and ffmpeg not found. Please install or provide the path using --ffmpeg-location | trace: {'filename': 'c:\\Users\\jhefe\\OneDrive\\Documentos\\GitHub\\SRBRONLINE\\RewardEvents\\RewardEvents.py', 'name': 'download_music', 'lineno': 3524} | time: 04/12/2022 11:36:17 
Erro = type: IndexError | message: list index out of range | trace: {'filename': 'c:\\Users\\jhefe\\OneDrive\\Documentos\\GitHub\\SRBRONLINE\\RewardEvents\\RewardEvents.py', 'name': 'command_fallback', 'lineno': 5082} | time: 04/12/2022 11:36:35 
Erro = type:WebSocketBadStatusException | message: Handshake status 200 OK | trace: [{'filename': 'c:\\Users\\jhefe\\OneDrive\\Documentos\\GitHub\\SRBRONLINE\\RewardEvents\\obs_events.py', 'name': 'notification', 'lineno': 219}, {'filename': 'C:\\Users\\jhefe\\OneDrive\\Documentos\\GitHub\\SRBRONLINE\\RewardEvents\\.venv\\Lib\\site-packages\\obsws_python\\reqs.py', 'name': '__init__', 'lineno': 18}, {'filename': 'C:\\Users\\jhefe\\OneDrive\\Documentos\\GitHub\\SRBRONLINE\\RewardEvents\\.venv\\Lib\\site-packages\\obsws_python\\baseclient.py', 'name': '__init__', 'lineno': 36}, {'filename': 'C:\\Users\\jhefe\\OneDrive\\Documentos\\GitHub\\SRBRONLINE\\RewardEvents\\.venv\\Lib\\site-packages\\websocket\\_core.py', 'name': 'connect', 'lineno': 253}, {'filename': 'C:\\Users\\jhefe\\OneDrive\\Documentos\\GitHub\\SRBRONLINE\\RewardEvents\\.venv\\Lib\\site-packages\\websocket\\_handshake.py', 'name': 'handshake', 'lineno': 57}, {'filename': 'C:\\Users\\jhefe\\OneDrive\\Documentos\\GitHub\\SRBRONLINE\\RewardEvents\\.venv\\Lib\\site-packages\\websocket\\_handshake.py', 'name': '_get_resp_headers', 'lineno': 147}] | time: 04/12/2022 11:38:51 
Erro = type: IndexError | message: list index out of range | trace: [{'filename': 'c:\\Users\\jhefe\\OneDrive\\Documentos\\GitHub\\SRBRONLINE\\RewardEvents\\RewardEvents.py', 'name': 'command_fallback', 'lineno': 5083}, {'filename': 'c:\\Users\\jhefe\\OneDrive\\Documentos\\GitHub\\SRBRONLINE\\RewardEvents\\RewardEvents.py', 'name': 'commands_module', 'lineno': 4873}] | time: 04/12/2022 11:39:00 
Erro = type:WebSocketBadStatusException | message: Handshake status 200 OK | trace: [{'filename': 'c:\\Users\\jhefe\\OneDrive\\Documentos\\GitHub\\SRBRONLINE\\RewardEvents\\obs_events.py', 'name': 'notification', 'lineno': 219}, {'filename': 'C:\\Users\\jhefe\\OneDrive\\Documentos\\GitHub\\SRBRONLINE\\RewardEvents\\.venv\\Lib\\site-packages\\obsws_python\\reqs.py', 'name': '__init__', 'lineno': 18}, {'filename': 'C:\\Users\\jhefe\\OneDrive\\Documentos\\GitHub\\SRBRONLINE\\RewardEvents\\.venv\\Lib\\site-packages\\obsws_python\\baseclient.py', 'name': '__init__', 'lineno': 36}, {'filename': 'C:\\Users\\jhefe\\OneDrive\\Documentos\\GitHub\\SRBRONLINE\\RewardEvents\\.venv\\Lib\\site-packages\\websocket\\_core.py', 'name': 'connect', 'lineno': 253}, {'filename': 'C:\\Users\\jhefe\\OneDrive\\Documentos\\GitHub\\SRBRONLINE\\RewardEvents\\.venv\\Lib\\site-packages\\websocket\\_handshake.py', 'name': 'handshake', 'lineno': 57}, {'filename': 'C:\\Users\\jhefe\\OneDrive\\Documentos\\GitHub\\SRBRONLINE\\RewardEvents\\.venv\\Lib\\site-packages\\websocket\\_handshake.py', 'name': '_get_resp_headers', 'lineno': 147}] | time: 04/12/2022 11:39:26 
Erro = type:WebSocketBadStatusException | message: Handshake status 200 OK | trace: [{'filename': 'c:\\Users\\jhefe\\OneDrive\\Documentos\\GitHub\\SRBRONLINE\\RewardEvents\\obs_events.py', 'name': 'notification', 'lineno': 219}, {'filename': 'C:\\Users\\jhefe\\OneDrive\\Documentos\\GitHub\\SRBRONLINE\\RewardEvents\\.venv\\Lib\\site-packages\\obsws_python\\reqs.py', 'name': '__init__', 'lineno': 18}, {'filename': 'C:\\Users\\jhefe\\OneDrive\\Documentos\\GitHub\\SRBRONLINE\\RewardEvents\\.venv\\Lib\\site-packages\\obsws_python\\baseclient.py', 'name': '__init__', 'lineno': 36}, {'filename': 'C:\\Users\\jhefe\\OneDrive\\Documentos\\GitHub\\SRBRONLINE\\RewardEvents\\.venv\\Lib\\site-packages\\websocket\\_core.py', 'name': 'connect', 'lineno': 253}, {'filename': 'C:\\Users\\jhefe\\OneDrive\\Documentos\\GitHub\\SRBRONLINE\\RewardEvents\\.venv\\Lib\\site-packages\\websocket\\_handshake.py', 'name': 'handshake', 'lineno': 57}, {'filename': 'C:\\Users\\jhefe\\OneDrive\\Documentos\\GitHub\\SRBRONLINE\\RewardEvents\\.venv\\Lib\\site-packages\\websocket\\_handshake.py', 'name': '_get_resp_headers', 'lineno': 147}] | time: 04/12/2022 12:08:07 
Erro = type:WebSocketBadStatusException | message: Handshake status 200 OK | trace: [{'filename': 'c:\\Users\\jhefe\\OneDrive\\Documentos\\GitHub\\SRBRONLINE\\RewardEvents\\obs_events.py', 'name': 'notification', 'lineno': 219}, {'filename': 'C:\\Users\\jhefe\\OneDrive\\Documentos\\GitHub\\SRBRONLINE\\RewardEvents\\.venv\\Lib\\site-packages\\obsws_python\\reqs.py', 'name': '__init__', 'lineno': 18}, {'filename': 'C:\\Users\\jhefe\\OneDrive\\Documentos\\GitHub\\SRBRONLINE\\RewardEvents\\.venv\\Lib\\site-packages\\obsws_python\\baseclient.py', 'name': '__init__', 'lineno': 36}, {'filename': 'C:\\Users\\jhefe\\OneDrive\\Documentos\\GitHub\\SRBRONLINE\\RewardEvents\\.venv\\Lib\\site-packages\\websocket\\_core.py', 'name': 'connect', 'lineno': 253}, {'filename': 'C:\\Users\\jhefe\\OneDrive\\Documentos\\GitHub\\SRBRONLINE\\RewardEvents\\.venv\\Lib\\site-packages\\websocket\\_handshake.py', 'name': 'handshake', 'lineno': 57}, {'filename': 'C:\\Users\\jhefe\\OneDrive\\Documentos\\GitHub\\SRBRONLINE\\RewardEvents\\.venv\\Lib\\site-packages\\websocket\\_handshake.py', 'name': '_get_resp_headers', 'lineno': 147}] | time: 04/12/2022 12:08:13 
Erro = type: DownloadError | message: ERROR: Postprocessing: ffprobe and ffmpeg not found. Please install or provide the path using --ffmpeg-location | trace: [{'filename': 'c:\\Users\\jhefe\\OneDrive\\Documentos\\GitHub\\SRBRONLINE\\RewardEvents\\RewardEvents.py', 'name': 'download_music', 'lineno': 3524}, {'filename': 'C:\\Users\\jhefe\\OneDrive\\Documentos\\GitHub\\SRBRONLINE\\RewardEvents\\.venv\\Lib\\site-packages\\yt_dlp\\YoutubeDL.py', 'name': 'download', 'lineno': 3322}, {'filename': 'C:\\Users\\jhefe\\OneDrive\\Documentos\\GitHub\\SRBRONLINE\\RewardEvents\\.venv\\Lib\\site-packages\\yt_dlp\\YoutubeDL.py', 'name': 'wrapper', 'lineno': 3297}, {'filename': 'C:\\Users\\jhefe\\OneDrive\\Documentos\\GitHub\\SRBRONLINE\\RewardEvents\\.venv\\Lib\\site-packages\\yt_dlp\\YoutubeDL.py', 'name': 'extract_info', 'lineno': 1474}, {'filename': 'C:\\Users\\jhefe\\OneDrive\\Documentos\\GitHub\\SRBRONLINE\\RewardEvents\\.venv\\Lib\\site-packages\\yt_dlp\\YoutubeDL.py', 'name': 'wrapper', 'lineno': 1485}, {'filename': 'C:\\Users\\jhefe\\OneDrive\\Documentos\\GitHub\\SRBRONLINE\\RewardEvents\\.venv\\Lib\\site-packages\\yt_dlp\\YoutubeDL.py', 'name': '__extract_info', 'lineno': 1582}, {'filename': 'C:\\Users\\jhefe\\OneDrive\\Documentos\\GitHub\\SRBRONLINE\\RewardEvents\\.venv\\Lib\\site-packages\\yt_dlp\\YoutubeDL.py', 'name': 'process_ie_result', 'lineno': 1641}, {'filename': 'C:\\Users\\jhefe\\OneDrive\\Documentos\\GitHub\\SRBRONLINE\\RewardEvents\\.venv\\Lib\\site-packages\\yt_dlp\\YoutubeDL.py', 'name': 'process_video_result', 'lineno': 2737}, {'filename': 'C:\\Users\\jhefe\\OneDrive\\Documentos\\GitHub\\SRBRONLINE\\RewardEvents\\.venv\\Lib\\site-packages\\yt_dlp\\YoutubeDL.py', 'name': 'process_info', 'lineno': 3278}, {'filename': 'C:\\Users\\jhefe\\OneDrive\\Documentos\\GitHub\\SRBRONLINE\\RewardEvents\\.venv\\Lib\\site-packages\\yt_dlp\\YoutubeDL.py', 'name': 'report_error', 'lineno': 1004}, {'filename': 'C:\\Users\\jhefe\\OneDrive\\Documentos\\GitHub\\SRBRONLINE\\RewardEvents\\.venv\\Lib\\site-packages\\yt_dlp\\YoutubeDL.py', 'name': 'trouble', 'lineno': 944}] | time: 04/12/2022 12:08:19 
Erro = type: UnboundLocalError | message: cannot access local variable 'name_to_add' where it is not associated with a value | trace: [{'filename': 'c:\\Users\\jhefe\\OneDrive\\Documentos\\GitHub\\SRBRONLINE\\RewardEvents\\RewardEvents.py', 'name': 'command_fallback', 'lineno': 5061}] | time: 04/12/2022 14:35:12 
Erro = type: InvalidTokenException | message: invalid access token | trace: [{'filename': 'c:\\Users\\jhefe\\OneDrive\\Documentos\\GitHub\\SRBRONLINE\\RewardEvents\\RewardEvents.py', 'name': 'start_auth_pub', 'lineno': 5256}, {'filename': 'C:\\Users\\jhefe\\OneDrive\\Documentos\\GitHub\\SRBRONLINE\\RewardEvents\\.venv\\Lib\\site-packages\\twitchAPI\\twitch.py', 'name': 'set_user_authentication', 'lineno': 462}] | time: 04/12/2022 14:41:47 
Erro = type: InvalidTokenException | message: invalid access token | trace: [{'filename': 'C:\\Users\\jhefe\\OneDrive\\Documentos\\GitHub\\SRBRONLINE\\RewardEvents\\RewardEvents.py', 'name': 'start_auth_pub', 'lineno': 5278}, {'filename': 'C:\\Users\\jhefe\\OneDrive\\Documentos\\GitHub\\SRBRONLINE\\RewardEvents\\env\\Lib\\site-packages\\twitchAPI\\twitch.py', 'name': 'set_user_authentication', 'lineno': 462}] | time: 05/12/2022 13:37:15 
Erro = type: NameError | message: name 'a' is not defined | trace: [{'filename': 'c:\\Users\\jhefe\\OneDrive\\Documentos\\GitHub\\SRBRONLINE\\RewardEvents\\error_logger.py', 'name': '<module>', 'lineno': 30}] | time: 05/12/2022 14:03:24 
Erro = type: InvalidTokenException | message: invalid access token | trace: [{'filename': 'c:\\Users\\jhefe\\OneDrive\\Documentos\\GitHub\\SRBRONLINE\\RewardEvents\\RewardEvents.py', 'name': 'start_auth_pub', 'lineno': 5179}, {'filename': 'C:\\Users\\jhefe\\OneDrive\\Documentos\\GitHub\\SRBRONLINE\\RewardEvents\\.venv\\Lib\\site-packages\\twitchAPI\\twitch.py', 'name': 'set_user_authentication', 'lineno': 462}] | time: 06/12/2022 02:59:28 
